
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[359] =
    {   0,
        0,    0,  113,  111,    5,    1,   46,  111,   58,   59,
       35,  111,  111,   51,   52,   33,   31,   53,   32,   49,
       34,   97,   57,   54,   41,   30,   40,   60,  110,  110,
       47,   61,   48,   62,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   55,  111,   56,    5,   39,    0,   98,    0,    0,
        2,  110,   44,    0,    0,  108,    0,    0,   36,   37,
        0,   97,   96,    0,    0,   95,   43,   38,   42,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
       68,  110,  110,  110,  110,  110,  110,  110,  110,   17,

      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   45,   98,    0,  101,    0,    0,  101,    0,    0,
        0,    0,    0,    0,    0,    3,    0,   95,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,   16,  110,
      110,  110,   19,  110,  110,  110,   21,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,   91,   92,  110,  110,  110,    0,
      109,  107,  105,  104,  106,  102,  103,    0,    4,  110,

      110,  110,  110,  110,   65,    8,  110,    9,  110,  110,
      110,  110,  110,   14,   69,  110,  110,  110,  110,  110,
       74,  110,  110,  110,  110,   20,  110,  110,   28,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   87,  110,  110,   99,   26,  110,  110,    0,  110,
      110,  110,  110,    7,   66,   10,   67,  110,  110,  110,
      110,  110,  100,   72,   15,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,   83,  110,  110,
       85,  110,  110,   88,  110,  110,   27,   50,   29,  110,
       64,  110,  110,  110,   13,  110,  110,  110,  110,   76,

      110,  110,   78,   79,  110,  110,  110,   22,  110,   23,
       24,  110,   25,  110,   89,  110,  110,  110,    6,  110,
       12,   70,   71,   73,  110,  110,  110,   80,   94,  110,
      110,  110,  110,  110,  110,   63,   11,  110,  110,  110,
      110,   82,   84,  110,  110,   93,  110,  110,   77,   81,
      110,   90,   75,   18,  110,  110,   86,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   28,   27,   27,   27,   27,   27,   27,   27,
       29,   30,   31,    1,   27,   32,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[368] =
    {   0,
        0,    0,  404,  405,   59,  405,  379,   56,  399,    0,
      405,  391,   61,  349,  405,  405,  384,  405,   48,  378,
       55,   53,  405,  405,  373,  372,  371,  405,    0,  343,
      405,  405,  405,  405,   33,   29,   44,   33,   37,   55,
      347,   55,  346,  345,   69,   56,  353,   63,   55,   48,
      349,  405,  329,  405,  105,  405,  104,  405,  105,  384,
      405,    0,  405,  375,  374,  373,  117,  327,  405,  405,
      362,   98,  361,  366,  109,  359,  405,  405,  405,  329,
      327,  326,  329,  337,  322,   74,  339,  338,  325,  331,
      316,  317,  314,   75,  322,  319,  317,  313,  310,    0,

      313,   79,  314,  322,  306,  302,  312,  319,   86,  319,
       85,  306,  104,  304,  309,  304,   90,  105,  299,   99,
      306,  405,  135,  335,  405,  334,  333,  332,  331,  330,
      329,  292,  324,  129,  141,  405,  146,  317,  295,  284,
      297,  290,  299,  294,  293,  294,  279,  277,  101,  293,
      291,  287,  279,  276,  284,  270,  286,  285,    0,  271,
      112,  265,  278,  275,  261,  271,    0,  268,  268,  256,
      257,  264,  254,  253,  255,  252,  261,  264,  249,  264,
      248,  251,  251,  258,    0,    0,  258,  260,  249,  280,
      405,  405,  405,  405,  405,  405,  405,  253,  405,  244,

      239,  238,  249,  243,    0,    0,  244,    0,  233,  231,
      240,  228,  236,    0,    0,  229,  232,  239,  232,  223,
        0,  236,  223,  238,  221,    0,  226,  215,    0,  234,
      233,  228,  223,  222,  213,  210,  219,  224,  209,  222,
      216,    0,  201,  204,    0,    0,  202,  215,  238,  211,
      216,  197,  214,    0,    0,    0,    0,  201,  202,  207,
      192,  206,    0,  198,    0,  196,  188,  193,  199,  199,
      198,  195,  182,  197,  196,  181,  184,    0,  193,  176,
        0,  186,  176,  174,  182,  181,    0,  405,    0,  186,
        0,  175,  167,  167,    0,  167,  166,  159,  177,    0,

      178,  179,    0,    0,  174,  173,  158,    0,  171,    0,
        0,  169,    0,  160,    0,  168,  161,  152,    0,  165,
        0,    0,    0,    0,  156,  163,  164,    0,    0,  161,
      147,  149,  150,  149,  156,    0,    0,  119,  121,  129,
      128,    0,    0,  122,  109,    0,  109,  118,    0,    0,
       97,    0,    0,    0,  109,   61,    0,  405,  168,  171,
       73,  174,  177,  180,  183,  186,  189
    } ;

static const flex_int16_t yy_def[368] =
    {   0,
      358,    1,  358,  358,  358,  358,  358,  359,  360,  361,
      358,  358,  362,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  361,  361,
      358,  358,  358,  358,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  358,  358,  358,  358,  358,  359,  358,  359,  360,
      358,  361,  358,  363,  363,  358,  364,  358,  358,  358,
      358,  358,  358,  365,  366,  358,  358,  358,  358,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  358,  359,  367,  358,  367,  367,  358,  367,  367,
      367,  358,  365,  365,  366,  358,  366,  358,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  367,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  358,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  358,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,    0,  358,  358,
      358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[466] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   29,
       42,   29,   43,   44,   45,   29,   46,   29,   47,   48,
       49,   29,   50,   51,   29,   29,   29,   52,   53,   54,
       55,   58,   55,   65,   70,   71,   81,   72,   74,   90,
       76,   66,   72,   75,   83,   62,   86,   84,   91,   92,
      119,   93,   82,   87,   85,   59,   88,   95,  108,   89,
       67,   94,  100,  120,  117,   96,  357,   97,  101,  102,

       98,  105,  112,  118,  109,  106,   55,  110,   55,   58,
      123,  136,  137,  113,  114,   76,  115,   72,  116,  124,
      107,  154,  127,  145,  146,  155,  170,  128,  162,  163,
      181,  171,  173,   59,   59,  174,  176,  183,  182,  187,
       58,  188,  134,  136,  137,  356,  129,  199,  136,  137,
      210,  211,  177,  355,  222,  354,  184,  223,  353,  352,
      185,  130,  351,  350,   59,  349,  348,  131,   57,  347,
       57,   60,   60,   60,   64,   64,   64,  124,  124,  124,
      126,  126,  126,  133,  133,  133,  135,  135,  135,  190,
      190,  190,  346,  345,  344,  343,  342,  341,  340,  339,

      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      191,  248,  247,  246,  245,  244,  243,  242,  241,  240,

      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  138,  134,  198,  197,
      196,  195,  194,  193,  192,  191,  189,  186,  180,  179,
      178,  175,  172,  169,  168,  167,  166,  165,  164,  161,
      160,  159,  158,  157,  156,  153,  152,  151,  150,  149,
      148,  147,  144,  143,  142,  141,  140,  139,  138,  134,
       73,   73,  132,  125,  358,  125,   61,  122,  121,  111,
      104,  103,   99,   80,   79,   78,   77,   73,   69,   68,

       63,   61,   56,  358,    3,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[466] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    8,    5,   13,   19,   19,   35,   19,   21,   38,
       22,   13,   22,   21,   36,  361,   37,   36,   38,   39,
       50,   39,   35,   37,   36,    8,   37,   40,   46,   37,
       13,   39,   42,   50,   49,   40,  356,   40,   42,   42,

       40,   45,   48,   49,   46,   45,   55,   46,   55,   57,
       59,   75,   75,   48,   48,   72,   48,   72,   48,   67,
       45,   94,   67,   86,   86,   94,  109,   67,  102,  102,
      117,  109,  111,   57,   59,  111,  113,  118,  117,  120,
      123,  120,  134,  135,  135,  355,   67,  134,  137,  137,
      149,  149,  113,  351,  161,  348,  118,  161,  347,  345,
      118,   67,  344,  341,  123,  340,  339,   67,  359,  338,
      359,  360,  360,  360,  362,  362,  362,  363,  363,  363,
      364,  364,  364,  365,  365,  365,  366,  366,  366,  367,
      367,  367,  335,  334,  333,  332,  331,  330,  327,  326,

      325,  320,  318,  317,  316,  314,  312,  309,  307,  306,
      305,  302,  301,  299,  298,  297,  296,  294,  293,  292,
      290,  286,  285,  284,  283,  282,  280,  279,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      264,  262,  261,  260,  259,  258,  253,  252,  251,  250,
      249,  248,  247,  244,  243,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  228,  227,  225,
      224,  223,  222,  220,  219,  218,  217,  216,  213,  212,
      211,  210,  209,  207,  204,  203,  202,  201,  200,  198,
      190,  189,  188,  187,  184,  183,  182,  181,  180,  179,

      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  166,  165,  164,  163,  162,  160,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  133,  132,  131,
      130,  129,  128,  127,  126,  124,  121,  119,  116,  115,
      114,  112,  110,  108,  107,  106,  105,  104,  103,  101,
       99,   98,   97,   96,   95,   93,   92,   91,   90,   89,
       88,   87,   85,   84,   83,   82,   81,   80,   76,   74,
       73,   71,   68,   66,   65,   64,   60,   53,   51,   47,
       44,   43,   41,   30,   27,   26,   25,   20,   17,   14,

       12,    9,    7,    3,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[113] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "j0lex.l"
/* -*-bison-*- */
/* Simple wc implementation in Flex */
#define YY_NO_INPUT 1
#line 9 "j0lex.l"
#include "defs.h"
#include "j0gram.tab.h"
extern int handle_token(int category_value);
int rows = 0, words = 0, chars = 0;
#line 702 "lex.yy.c"
#line 703 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "j0lex.l"

#line 920 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 405 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "j0lex.l"
{/*discard comment */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 17 "j0lex.l"
{ /* no-op, discard comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 18 "j0lex.l"
{/* no-op, discard single line comment */}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 19 "j0lex.l"
{ /*discard multi-line comment */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "j0lex.l"
{ /*discard whitespace */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "j0lex.l"
{ return handle_token(BOOL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "j0lex.l"
{ return handle_token(BREAK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "j0lex.l"
{ return handle_token(CASE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "j0lex.l"
{ return handle_token(CHAR); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "j0lex.l"
{ return handle_token(CLASS); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "j0lex.l"
{ return handle_token(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "j0lex.l"
{ return handle_token(DEFAULT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "j0lex.l"
{ return handle_token(DOUBLE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "j0lex.l"
{ return handle_token(ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 31 "j0lex.l"
{ return handle_token(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "j0lex.l"
{ return handle_token(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "j0lex.l"
{ return handle_token(IF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "j0lex.l"
{ return handle_token(INSTANCEOF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "j0lex.l"
{ return handle_token(INT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "j0lex.l"
{ return handle_token(LONG); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "j0lex.l"
{ return handle_token(NEW); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "j0lex.l"
{ return handle_token(PUBLIC); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "j0lex.l"
{ return handle_token(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "j0lex.l"
{ return handle_token(STATIC); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "j0lex.l"
{ return handle_token(SWITCH); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "j0lex.l"
{ return handle_token(VOID); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 43 "j0lex.l"
{ return handle_token(WHILE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 44 "j0lex.l"
{ return handle_token(NULLVAL);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 45 "j0lex.l"
{ return handle_token(STRING); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "j0lex.l"
{ return handle_token('='); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "j0lex.l"
{ return handle_token('+'); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "j0lex.l"
{ return handle_token('-'); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "j0lex.l"
{ return handle_token('*'); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "j0lex.l"
{ return handle_token('/'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "j0lex.l"
{ return handle_token('%'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "j0lex.l"
{ return handle_token(INCREMENT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "j0lex.l"
{ return handle_token(DECREMENT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "j0lex.l"
{ return handle_token(ISEQUALTO); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "j0lex.l"
{ return handle_token(NOTEQUALTO); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "j0lex.l"
{ return handle_token('>'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "j0lex.l"
{ return handle_token('<'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "j0lex.l"
{ return handle_token(GREATERTHANOREQUAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "j0lex.l"
{ return handle_token(LESSTHANOREQUAL); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "j0lex.l"
{ return handle_token(LOGICALAND); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "j0lex.l"
{ return handle_token(LOGICALOR); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "j0lex.l"
{ return handle_token(LOGICALNOT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "j0lex.l"
{ return handle_token('['); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "j0lex.l"
{ return handle_token(']'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "j0lex.l"
{ return handle_token('.'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 68 "j0lex.l"
{ return handle_token(TYPE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "j0lex.l"
{ return handle_token('('); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "j0lex.l"
{ return handle_token(')'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "j0lex.l"
{ return handle_token(','); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "j0lex.l"
{ return handle_token(';'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "j0lex.l"
{ return handle_token('{'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "j0lex.l"
{ return handle_token('}'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "j0lex.l"
{ return handle_token(':'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 117 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 "j0lex.l"
{return handle_token(REALLIT); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 120 "j0lex.l"
{return handle_token(REALLIT); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 121 "j0lex.l"
{ return handle_token(INTLIT); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 122 "j0lex.l"
{ return handle_token(STRINGLIT); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 123 "j0lex.l"
{ return handle_token(BOOLLIT); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 124 "j0lex.l"
{ return handle_token(BOOLLIT); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 127 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 128 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 129 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 130 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 131 "j0lex.l"
{ return handle_token(INVALID_CHARLIT_ESCAPE); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 132 "j0lex.l"
{ return handle_token(EMPTY_CHARLIT); }
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 133 "j0lex.l"
{ return handle_token(OPENENDED_CHARLIT); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "j0lex.l"
{ return handle_token(IDENTIFIER); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 136 "j0lex.l"
{ chars++; return handle_token(UNRECOGNIZED_CHARACTER); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 137 "j0lex.l"
ECHO;
	YY_BREAK
#line 1552 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 137 "j0lex.l"


