typedef enum {
	TOKEN = 100,
	prodR_ClassBodyDecls,
	prodR_FieldDecl,
	prodR_VarDecls,
	prodR_MethodHeader,
	prodR_FormalParmList,
	prodR_ConstructorDecl,
	prodR_BlockStmts,
	prodR_IfThenStmt,
	prodR_IfThenElseStmt,
	prodR_IfThenElseIfStmt,
	prodR_ElseIfSequence,
	prodR_WhileStmt,
	prodR_ForStmt,
	prodR_StmtExprList,
	prodR_InstantiationExpr,
	prodR_ArgList,
	prodR_MethodCall,
	prodR_MulExpr,
	prodR_AddExpr,
	prodR_RelExpr,
	prodR_EqExpr,
	prodR_CondAndExpr,
	prodR_CondOrExpr,
	prodR_Assignment,
} prodrule;
