
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[343] =
    {   0,
        0,    0,  109,  106,    4,    1,   43,  106,   55,   56,
       32,  106,  106,   48,   49,   30,   28,   50,   29,   46,
       31,   94,   54,   51,   38,   27,   37,   57,  106,   44,
       58,   45,   59,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
       52,  106,   53,    4,   36,    0,   95,    0,    0,    2,
       41,    0,  105,    0,    0,   33,   34,    0,   94,   93,
        0,   92,   94,  107,   40,   35,   39,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   65,  107,  107,
      107,  107,  107,  107,  107,  107,   16,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   42,   95,   98,
        0,    0,   98,    0,    0,    0,    0,    0,    0,   92,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,   15,
      107,  107,  107,   18,  107,  107,  107,   20,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,   88,   89,  107,  107,  107,  104,
      102,  101,  103,   99,  100,    0,    3,  107,  107,  107,
      107,   62,    7,  107,    8,  107,  107,  107,  107,  107,

       13,   66,  107,  107,  107,  107,  107,   71,  107,  107,
      107,  107,   19,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   84,  107,  107,
       96,   25,  107,  107,    0,  107,  107,  107,    6,   63,
        9,   64,  107,  107,  107,  107,  107,   97,   69,   14,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,   80,  107,  107,   82,  107,  107,   85,  107,
      107,   26,   47,  107,   61,  107,  107,  107,   12,  107,
      107,  107,  107,   73,  107,  107,   75,   76,  107,  107,
      107,   21,  107,   22,   23,  107,   24,  107,   86,  107,

      107,  107,    5,  107,   11,   67,   68,   70,  107,  107,
      107,   77,   91,  107,  107,  107,  107,  107,  107,   60,
       10,  107,  107,  107,  107,   79,   81,  107,  107,   90,
      107,  107,   74,   78,  107,   87,   72,   17,  107,  107,
       83,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,    1,   30,   31,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   26,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    3,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[349] =
    {   0,
        0,    0,  632,  633,  629,  633,  607,   55,  626,  633,
      633,  619,   51,  577,  633,  633,  612,  633,   46,  606,
      611,   47,  633,  633,  600,  599,  598,  633,  603,  633,
      633,  633,  633,   51,   50,   54,   52,   59,   70,   61,
       74,   63,   64,   53,   75,   58,   97,  103,   87,   99,
      633,  561,  633,  616,  633,  116,  633,  117,  614,  633,
      633,  606,  605,  125,  559,  633,  633,  594,   55,  593,
      598,  591,  108,  592,  633,  633,  633,  107,  111,  112,
      122,  114,  116,  117,  123,  124,  126,  120,  129,  137,
      144,  142,  145,  150,  153,  155,  591,  156,  157,  159,

      162,  160,  163,   56,  164,  165,  168,  166,  176,  174,
      179,  169,  182,  195,  175,  197,  200,  633,  216,  633,
      597,  596,  595,  594,  593,  592,  555,  587,   64,  580,
      183,  209,  211,  215,  212,  218,  208,  214,  217,  219,
      224,  226,  221,  232,  234,  235,  238,  241,  244,  581,
      243,  247,  246,  248,  253,  250,  255,  580,  257,  260,
      261,  263,  264,  265,  266,  268,  269,  277,  273,  276,
      280,  282,  286,  283,  579,  578,  285,  289,  290,  633,
      633,  633,  633,  633,  633,  558,  633,  287,  291,  300,
      305,  576,  575,  308,  574,  307,  309,  311,  314,  316,

      573,  572,  320,  317,  321,  324,  323,  571,  326,  327,
      328,  331,  570,  325,  332,  337,  338,  335,  336,  346,
      333,  347,  355,  357,  360,  365,  361,  569,  363,  366,
      568,  567,  368,  370,  571,  371,  372,  373,  565,  564,
      563,  562,  375,  379,  376,  377,  385,  561,  381,  560,
      387,  384,  392,  394,  390,  393,  397,  396,  407,  408,
      400,  411,  559,  415,  416,  558,  420,  421,  422,  423,
      427,  557,  633,  426,  556,  428,  430,  433,  555,  435,
      436,  434,  437,  554,  440,  444,  549,  546,  439,  441,
      445,  540,  451,  537,  536,  453,  535,  447,  534,  461,

      462,  448,  533,  463,  532,  531,  530,  527,  465,  469,
      474,  526,  525,  471,  476,  477,  483,  484,  479,  524,
      523,  485,  486,  493,  489,  522,  521,  494,  495,  515,
      497,  496,  513,  509,  499,  505,  504,  503,  500,  502,
      501,  633,  555,  558,  561,  184,  564,  567
    } ;

static const flex_int16_t yy_def[349] =
    {   0,
      342,    1,  342,  342,  342,  342,  342,  343,  344,  342,
      342,  342,  345,  342,  342,  342,  342,  342,  342,  342,
      342,  346,  342,  342,  342,  342,  342,  342,  346,  342,
      342,  342,  342,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      342,  342,  342,  342,  342,  343,  342,  343,  344,  342,
      342,  342,  342,  347,  342,  342,  342,  342,  342,  342,
      348,  342,  346,  346,  342,  342,  342,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  342,  343,  342,
      342,  342,  342,  342,  342,  342,  342,  348,  348,  342,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  342,
      342,  342,  342,  342,  342,  342,  342,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  342,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  342,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,    0,  342,  342,  342,  342,  342,  342
    } ;

static const flex_int16_t yy_nxt[693] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,    4,
       33,   34,   35,   36,   37,   38,   39,   40,   29,   41,
       29,   42,   43,   44,   29,   45,   29,   46,   47,   48,
       29,   49,   50,   29,   29,   29,   51,   52,   53,   57,
       63,   67,   68,   72,   69,   73,  342,  342,  342,  342,
      342,   72,  342,   69,  342,  342,  129,  342,   64,  342,
      342,  187,   58,   78,  102,   83,  342,   87,  103,  159,
      342,  342,   84,  107,   80,   85,   88,   81,   86,   79,

       89,   92,   90,  342,   82,   96,  104,  100,  101,   93,
       97,   94,   91,  342,   95,  342,   98,   99,  115,  342,
       57,  119,  105,  342,   72,  106,   73,  342,  342,  122,
      342,  116,  342,  342,  123,  108,  342,  117,  342,  342,
      342,  113,  342,   58,   58,  342,  109,  110,  138,  111,
      114,  112,  124,  342,  139,  131,  133,  134,  342,  132,
      342,  342,  141,  135,  136,  137,  342,  140,  125,  342,
      142,  342,  342,  342,  126,  342,  342,  143,  342,  342,
      342,  342,  342,  147,  342,  342,   74,  144,  148,  145,
      342,  342,  342,  146,  149,  342,  156,  162,  342,  342,

      150,  152,  155,  160,  151,  153,  154,  166,  161,  157,
      165,  342,  170,  342,  163,  158,  342,  164,  169,  168,
       57,  171,  176,  167,  342,  342,  173,  342,  342,  172,
      342,  342,  188,  342,  342,  342,  177,  342,  178,  179,
      342,  194,  342,   58,  189,  174,  191,  192,  342,  175,
      342,  342,  190,  193,  342,  199,  201,  342,  200,  342,
      342,  195,  342,  342,  342,  196,  342,  197,  198,  342,
      204,  342,  206,  342,  202,  207,  342,  342,  203,  342,
      342,  342,  342,  212,  342,  342,  205,  208,  209,  342,
      213,  210,  342,  342,  215,  211,  342,  216,  342,  342,

      214,  342,  342,  342,  219,  342,  342,  342,  224,  227,
      218,  217,  225,  222,  220,  221,  342,  223,  231,  232,
      233,  342,  226,  342,  342,  342,  229,  342,  228,  230,
      342,  234,  342,  342,  236,  238,  342,  342,  237,  342,
      342,  342,  342,  342,  342,  239,  240,  342,  342,  342,
      243,  342,  342,  342,  342,  241,  248,  245,  242,  253,
      247,  251,  342,  342,  244,  249,  255,  246,  257,  258,
      259,  342,  250,  342,  252,  260,  342,  342,  254,  342,
      262,  342,  342,  256,  342,  261,  342,  342,  342,  342,
      265,  342,  342,  342,  264,  342,  263,  342,  267,  268,

      342,  342,  274,  342,  276,  272,  342,  266,  342,  342,
      342,  279,  342,  342,  270,  269,  342,  271,  277,  281,
      278,  275,  282,  342,  342,  287,  280,  342,  288,  283,
      286,  342,  342,  284,  289,  285,  342,  342,  342,  342,
      291,  292,  342,  342,  342,  290,  342,  293,  295,  342,
      342,  342,  342,  342,  294,  342,  342,  342,  297,  302,
      342,  342,  300,  342,  342,  296,  301,  342,  298,  342,
      299,  303,  309,  310,  312,  311,  313,  342,  342,  342,
      304,  342,  305,  306,  307,  342,  315,  342,  308,  316,
      342,  317,  342,  342,  314,  342,  318,  320,  321,  342,

      342,  342,  342,  319,  323,  342,  325,  324,  322,  342,
      342,  342,  342,  342,  330,  342,  342,  342,  342,  342,
      342,  342,  327,  334,  326,  342,  328,  329,  333,  342,
      332,  342,  338,  335,  331,  340,  341,  342,  342,  342,
      342,  342,  342,  342,  336,  337,  342,  342,  342,  342,
      342,  342,  342,  342,  339,   56,  342,   56,   59,   59,
       59,   62,  342,   62,  121,  342,  121,  128,  128,  128,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  273,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  235,  342,  342,  342,  342,  130,  129,

      186,  185,  184,  183,  182,  181,  180,  342,  342,  130,
      129,   70,   70,  127,  120,  120,   60,   54,  118,  342,
       77,   76,   75,   71,   70,   66,   65,   61,   60,   55,
       54,  342,    3,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342

    } ;

static const flex_int16_t yy_chk[693] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       13,   19,   19,   22,   19,   22,   35,   34,   37,   44,
       36,   69,  104,   69,   46,   38,  129,   40,   13,   42,
       43,  129,    8,   34,   44,   36,   39,   37,   44,  104,
       41,   45,   36,   46,   35,   36,   37,   35,   36,   34,

       38,   39,   38,   49,   35,   40,   45,   42,   43,   39,
       41,   39,   38,   47,   39,   50,   41,   41,   49,   48,
       56,   58,   45,   78,   73,   45,   73,   79,   80,   64,
       82,   49,   83,   84,   64,   47,   88,   50,   81,   85,
       86,   48,   87,   56,   58,   89,   47,   47,   84,   47,
       48,   47,   64,   90,   85,   78,   80,   81,   92,   79,
       91,   93,   87,   82,   83,   83,   94,   86,   64,   95,
       88,   96,   98,   99,   64,  100,  102,   89,  101,  103,
      105,  106,  108,   92,  107,  112,  346,   90,   93,   91,
      110,  115,  109,   91,   94,  111,  101,  106,  113,  131,

       95,   98,  100,  105,   96,   99,   99,  109,  105,  102,
      108,  114,  112,  116,  107,  103,  117,  107,  111,  110,
      119,  113,  115,  109,  137,  132,  114,  133,  135,  113,
      138,  134,  131,  139,  136,  140,  116,  143,  116,  117,
      141,  137,  142,  119,  132,  114,  134,  135,  144,  114,
      145,  146,  133,  136,  147,  141,  143,  148,  142,  151,
      149,  138,  153,  152,  154,  139,  156,  140,  140,  155,
      146,  157,  148,  159,  144,  149,  160,  161,  145,  162,
      163,  164,  165,  154,  166,  167,  147,  151,  152,  169,
      155,  152,  170,  168,  157,  153,  171,  159,  172,  174,

      156,  177,  173,  188,  162,  178,  179,  189,  167,  170,
      161,  160,  168,  165,  163,  164,  190,  166,  174,  177,
      178,  191,  169,  196,  194,  197,  172,  198,  171,  173,
      199,  179,  200,  204,  188,  190,  203,  205,  189,  207,
      206,  214,  209,  210,  211,  191,  194,  212,  215,  221,
      198,  218,  219,  216,  217,  196,  205,  200,  197,  211,
      204,  209,  220,  222,  199,  206,  214,  203,  216,  217,
      218,  223,  207,  224,  210,  219,  225,  227,  212,  229,
      221,  226,  230,  215,  233,  220,  234,  236,  237,  238,
      224,  243,  245,  246,  223,  244,  222,  249,  226,  227,

      252,  247,  236,  251,  238,  234,  255,  225,  253,  256,
      254,  245,  258,  257,  230,  229,  261,  233,  243,  247,
      244,  237,  249,  259,  260,  255,  246,  262,  256,  251,
      254,  264,  265,  252,  257,  253,  267,  268,  269,  270,
      259,  260,  274,  271,  276,  258,  277,  261,  264,  278,
      282,  280,  281,  283,  262,  289,  285,  290,  267,  274,
      286,  291,  270,  298,  302,  265,  271,  293,  268,  296,
      269,  276,  283,  285,  289,  286,  290,  300,  301,  304,
      277,  309,  278,  280,  281,  310,  293,  314,  282,  296,
      311,  298,  315,  316,  291,  319,  300,  302,  304,  317,

      318,  322,  323,  301,  310,  325,  314,  311,  309,  324,
      328,  329,  332,  331,  319,  335,  339,  341,  340,  338,
      337,  336,  316,  325,  315,  334,  317,  318,  324,  333,
      323,  330,  332,  328,  322,  339,  340,  327,  326,  321,
      320,  313,  312,  308,  329,  331,  307,  306,  305,  303,
      299,  297,  295,  294,  335,  343,  292,  343,  344,  344,
      344,  345,  288,  345,  347,  287,  347,  348,  348,  348,
      284,  279,  275,  272,  266,  263,  250,  248,  242,  241,
      240,  239,  235,  232,  231,  228,  213,  208,  202,  201,
      195,  193,  192,  186,  176,  175,  158,  150,  130,  128,

      127,  126,  125,  124,  123,  122,  121,   97,   74,   72,
       71,   70,   68,   65,   63,   62,   59,   54,   52,   29,
       27,   26,   25,   21,   20,   17,   14,   12,    9,    7,
        5,    3,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[109] =
    {   0,
1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "j0lex.l"
/* -*-bison-*- */
/* Simple wc implementation in Flex */
#define YY_NO_INPUT 1
#line 9 "j0lex.l"
#include "j0gram.tab.h"
extern int handle_token(int category_value);
int rows = 0, words = 0, chars = 0;
#line 748 "lex.yy.c"
#line 749 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 14 "j0lex.l"

#line 966 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 343 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 633 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "j0lex.l"
{/*discard comment */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 16 "j0lex.l"
{ /* no-op, discard comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 17 "j0lex.l"
{ /*discard multi-line comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "j0lex.l"
{ /*discard whitespace */ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 20 "j0lex.l"
{ return YYEOF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "j0lex.l"
{ return handle_token(BOOL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "j0lex.l"
{ return handle_token(BREAK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "j0lex.l"
{ return handle_token(CASE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "j0lex.l"
{ return handle_token(CHAR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "j0lex.l"
{ return handle_token(CLASS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "j0lex.l"
{ return handle_token(CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "j0lex.l"
{ return handle_token(DEFAULT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "j0lex.l"
{ return handle_token(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "j0lex.l"
{ return handle_token(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "j0lex.l"
{ return handle_token(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 31 "j0lex.l"
{ return handle_token(FOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "j0lex.l"
{ return handle_token(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "j0lex.l"
{ return handle_token(INSTANCEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "j0lex.l"
{ return handle_token(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "j0lex.l"
{ return handle_token(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "j0lex.l"
{ return handle_token(NEW); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "j0lex.l"
{ return handle_token(PUBLIC); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "j0lex.l"
{ return handle_token(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "j0lex.l"
{ return handle_token(STATIC); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "j0lex.l"
{ return handle_token(SWITCH); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "j0lex.l"
{ return handle_token(VOID); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "j0lex.l"
{ return handle_token(WHILE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "j0lex.l"
{ return handle_token(atoi("=")); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "j0lex.l"
{ return handle_token(atoi("+")); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "j0lex.l"
{ return handle_token(atoi("-")); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "j0lex.l"
{ return handle_token(atoi("")); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "j0lex.l"
{ return handle_token(atoi("/")); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "j0lex.l"
{ return handle_token(atoi("%")); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "j0lex.l"
{ return handle_token(INCREMENT); } // remove based off txtbook?
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "j0lex.l"
{ return handle_token(DECREMENT); } // remove based off txtbook?
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "j0lex.l"
{ return handle_token(ISEQUALTO); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "j0lex.l"
{ return handle_token(NOTEQUALTO); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "j0lex.l"
{ return handle_token(atoi(">")); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "j0lex.l"
{ return handle_token(atoi("<")); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "j0lex.l"
{ return handle_token(GREATERTHANOREQUAL); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "j0lex.l"
{ return handle_token(LESSTHANOREQUAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "j0lex.l"
{ return handle_token(LOGICALAND); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "j0lex.l"
{ return handle_token(LOGICALOR); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "j0lex.l"
{ return handle_token(LOGICALNOT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "j0lex.l"
{ return handle_token(atoi("[")); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "j0lex.l"
{ return handle_token(atoi("]")); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "j0lex.l"
{ return handle_token(atoi(".")); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "j0lex.l"
{ return handle_token(TYPE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "j0lex.l"
{ return handle_token(atoi("(")); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "j0lex.l"
{ return handle_token(atoi(")")); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "j0lex.l"
{ return handle_token(atoi(",")); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "j0lex.l"
{ return handle_token(atoi(";")); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "j0lex.l"
{ return handle_token(atoi("{")); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "j0lex.l"
{ return handle_token(atoi("}")); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "j0lex.l"
{ return handle_token(atoi(":")); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "j0lex.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "j0lex.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 "j0lex.l"
{return handle_token(REALLIT); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 "j0lex.l"
{return handle_token(REALLIT); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 "j0lex.l"
{ return handle_token(INTLIT); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 "j0lex.l"
{ return handle_token(STRINGLIT); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 120 "j0lex.l"
{ return handle_token(BOOLLIT); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 121 "j0lex.l"
{ return handle_token(BOOLLIT); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 122 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 123 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 124 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 127 "j0lex.l"
{ return handle_token(CHARLIT); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 128 "j0lex.l"
{ return handle_token(INVALIDCHARLIT); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 129 "j0lex.l"
{ return handle_token(INVALIDCHARLIT); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "j0lex.l"
{ chars++; return handle_token(UNRECOGNIZED_CHARACTER); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "j0lex.l"
{ return handle_token(IDENTIFIER); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "j0lex.l"
ECHO;
	YY_BREAK
#line 1580 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 343 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 343 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 342);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "j0lex.l"


