
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[348] =
    {   0,
        0,    0,  107,  105,    4,    1,   45,  105,   67,   68,
       34,  105,  105,   60,   61,   32,   30,   62,   31,   48,
       33,   28,   66,   63,   40,   29,   39,   69,  104,   46,
       70,   47,   71,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
       64,  105,   65,   67,    4,   38,    0,   50,    0,   43,
        0,   56,    0,    0,   35,   36,   28,   27,    0,    0,
       28,  104,   42,   37,   41,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   77,  104,  104,  104,  104,
      104,  104,  104,  104,   16,  104,  104,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   44,    2,    0,   50,    0,
       51,    0,   51,    0,    0,    0,   27,    0,    0,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,   15,  104,
      104,  104,   18,  104,  104,  104,   20,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  100,  101,  104,  104,  104,    0,   59,
       55,   54,   52,   53,    0,   27,    3,  104,  104,  104,
      104,   74,    7,  104,    8,  104,  104,  104,  104,  104,

       13,   78,  104,  104,  104,  104,  104,   83,  104,  104,
      104,  104,   19,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,   96,  104,  104,
       57,   25,  104,  104,    0,    0,   27,  104,  104,  104,
        6,   75,    9,   76,  104,  104,  104,  104,  104,   58,
       81,   14,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   92,  104,  104,   94,  104,  104,
       97,  104,  104,   26,   49,   27,  104,   73,  104,  104,
      104,   12,  104,  104,  104,  104,   85,  104,  104,   87,
       88,  104,  104,  104,   21,  104,   22,   23,  104,   24,

      104,   98,  104,  104,   27,  104,    5,  104,   11,   79,
       80,   82,  104,  104,  104,   89,  103,  104,  104,  104,
      104,  104,  104,   27,   72,   10,  104,  104,  104,  104,
       91,   93,  104,  104,  102,  104,  104,   86,   90,  104,
       99,   84,   17,  104,  104,   95,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,    1,    1,   30,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    3,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[356] =
    {   0,
        0,  637,  642,  644,  639,  644,  617,   54,  644,  644,
      644,  630,   50,  589,  644,  644,  623,  644,   45,  617,
      622,   46,  644,  644,  611,  610,  609,  644,  614,  644,
      644,  644,  644,   45,   50,   54,   52,   58,   69,   59,
       73,   62,   63,   53,   74,   85,   95,  101,   97,   51,
      644,  573,  644,    0,  627,  644,  623,  644,   69,  644,
      617,  616,  112,  571,  644,  644,  605,  604,  609,  602,
       64,  603,  644,  644,  644,  102,  106,  108,  118,  109,
      114,  112,  115,  113,  121,  110,  117,  119,  123,  125,
      134,  120,  142,  150,  602,  153,  154,  157,  156,  158,

      159,  161,  162,  163,  164,  165,  174,  167,  169,  171,
      176,  166,  170,  187,  179,  644,    0,  214,  217,  608,
      607,  606,  605,  604,  603,  567,  592,  597,  211,  208,
      213,  210,  215,  214,  217,  220,  216,  218,  219,  223,
      224,  226,  222,  221,  227,  230,  238,  241,  592,  233,
      242,  243,  253,  254,  256,  257,  591,  258,  259,  262,
      263,  264,  265,  270,  267,  268,  273,  272,  276,  277,
      278,  280,  283,  590,  589,  285,  282,  286,    0,  595,
      594,  593,  592,  591,  565,  580,  644,  284,  288,  295,
      303,  581,  580,  307,  579,  309,  311,  312,  315,  317,

      578,  577,  316,  319,  320,  323,  321,  576,  324,  322,
      325,  327,  575,  330,  329,  335,  336,  333,  337,  344,
      331,  332,  355,  356,  358,  360,  362,  574,  365,  367,
      573,  572,  369,  368,  382,  576,  568,  371,  373,  375,
      569,  568,  567,  566,  378,  379,  374,  380,  382,  565,
      384,  564,  381,  387,  390,  391,  395,  396,  397,  394,
      402,  407,  409,  411,  563,  415,  420,  562,  421,  424,
      422,  425,  427,  561,  644,  558,  428,  559,  429,  430,
      432,  558,  434,  435,  433,  438,  556,  441,  436,  550,
      544,  440,  443,  445,  541,  451,  535,  534,  448,  533,

      446,  532,  460,  459,  529,  462,  530,  468,  529,  528,
      527,  524,  471,  472,  475,  523,  522,  474,  476,  480,
      479,  484,  481,  644,  521,  520,  482,  485,  488,  487,
      517,  516,  489,  493,  513,  495,  496,  509,  503,  498,
      501,  175,  168,  500,  502,   56,  644,  553,  556,   63,
      559,  562,  565,  568,  571
    } ;

static const flex_int16_t yy_def[356] =
    {   0,
      347,    1,  347,  347,  347,  347,  347,  348,  347,  347,
      347,  347,  349,  347,  347,  347,  347,  347,  347,  347,
      347,  350,  347,  347,  347,  347,  347,  347,  350,  347,
      347,  347,  347,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      347,  347,  347,  351,  347,  347,  348,  347,  352,  347,
      353,  353,  353,  347,  347,  347,  347,  347,  354,  347,
      350,  350,  347,  347,  347,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  347,  351,  348,  347,  353,
      353,  353,  353,  353,  353,  347,  347,  354,  354,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  355,  353,
      353,  353,  353,  353,  347,  347,  347,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  347,  347,  347,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  347,  347,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  347,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  347,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,    0,  347,  347,  347,
      347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[703] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   29,   41,   29,
       42,   43,   44,   29,   45,   29,   46,   47,   48,   29,
       49,   50,   29,   29,   29,   51,   52,   53,   58,   62,
       66,  347,   70,   67,   71,   72,  347,  347,  347,  347,
      347,   57,  347,  119,  347,  347,   76,   63,  347,  347,
       70,   59,   71,  100,   81,  347,   85,  101,  115,  347,
      347,   82,   77,   78,   83,   86,   79,   84,   87,   90,

       88,  347,   94,   80,  102,   98,   99,   91,   95,   92,
       89,  347,   93,  347,   96,   97,  122,  347,  347,  105,
      103,  123,  347,  104,  347,  347,  347,  113,  347,  347,
      347,  347,  106,  347,  347,  347,  347,  347,  111,  347,
      114,  347,  137,  107,  108,  138,  109,  112,  110,  130,
      347,  132,  133,  131,  124,  139,  140,  134,  347,  141,
      125,  135,  136,  148,  142,  146,  347,  144,  143,  347,
      347,  145,  347,  347,  347,  347,  147,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  149,  155,
      347,  347,  347,  158,  161,  347,  172,  151,  150,  154,

      159,  152,  153,  347,  165,  160,  156,  168,  164,  162,
      157,  167,  163,  169,  170,  173,  175,  178,   58,  174,
      166,   58,  171,  129,  347,  176,  347,  177,  187,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,   59,  347,  347,  179,  191,  347,  189,  192,  347,
      190,  193,  194,  199,  347,  200,  188,  347,  347,  347,
      201,  204,  195,  202,  203,  196,  197,  198,  206,  347,
      347,  207,  347,  347,  347,  347,  208,  205,  347,  347,
      347,  347,  209,  347,  347,  210,  347,  212,  347,  347,
      213,  211,  347,  347,  347,  215,  347,  216,  347,  347,

      347,  347,  347,  219,  347,  214,  224,  225,  227,  217,
      218,  347,  233,  220,  221,  223,  222,  231,  232,  347,
      226,  229,  230,  347,  228,  347,  234,  347,  347,  240,
      238,  347,  347,  347,  239,  347,  347,  347,  347,  347,
      347,  347,  241,  347,  242,  347,  347,  347,  347,  347,
      245,  347,  347,  347,  250,  255,  243,  247,  253,  244,
      347,  249,  248,  251,  246,  259,  260,  261,  254,  252,
      257,  347,  347,  256,  347,  262,  347,  264,  347,  258,
      265,  347,  263,  347,  347,  347,   58,  347,  267,  347,
      347,  347,  269,  266,  347,  347,  347,  347,  347,  270,

      347,  277,  274,  347,  268,  279,  347,  347,  282,  179,
      347,  347,  347,  347,  272,  284,  271,  273,  347,  281,
      280,  278,  286,  347,  285,  347,  289,  347,  283,  290,
      291,  347,  288,  292,  294,  287,  347,  347,  347,  295,
      347,  347,  293,  347,  347,  347,  347,  298,  347,  347,
      347,  347,  347,  297,  347,  296,  347,  347,  300,  347,
      306,  347,  347,  303,  347,  304,  315,  347,  299,  302,
      301,  307,  313,  314,  316,  347,  347,  317,  347,  308,
      309,  310,  311,  320,  347,  319,  312,  347,  347,  321,
      347,  347,  347,  318,  322,  347,  347,  347,  347,  323,

      347,  347,  326,  347,  347,  347,  328,  329,  330,  347,
      325,  347,  347,  327,  347,  335,  347,  347,  347,  347,
      339,  333,  338,  331,  332,  347,  334,  340,  337,  347,
      336,  343,  347,  347,  345,  346,  347,  347,  347,  347,
      347,  341,  342,  347,  347,  347,  347,  324,  347,  347,
      347,  347,  344,   57,   57,   57,   61,  347,   61,  117,
      347,  117,  118,  118,  118,  120,  347,  120,  128,  128,
      128,  235,  347,  235,  347,  347,  305,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  276,  275,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  237,  236,

      180,  180,  180,  180,  180,  347,  347,  347,  347,  129,
      186,  185,  184,  183,  182,  181,  180,  180,  347,  347,
       68,  129,  127,   67,  126,  121,  121,   58,   55,  116,
      347,   75,   74,   73,   69,   68,   65,   64,   60,   56,
       55,  347,   54,    3,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347
    } ;

static const flex_int16_t yy_chk[703] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   13,
       19,   34,   22,   19,   22,  350,   35,   50,   37,   44,
       36,   59,  346,   59,   38,   40,   34,   13,   42,   43,
       71,    8,   71,   44,   36,   39,   37,   44,   50,   41,
       45,   36,   34,   35,   36,   37,   35,   36,   38,   39,

       38,   46,   40,   35,   45,   42,   43,   39,   41,   39,
       38,   47,   39,   49,   41,   41,   63,   48,   76,   46,
       45,   63,   77,   45,   78,   80,   86,   49,   82,   84,
       81,   83,   47,   87,   79,   88,   92,   85,   48,   89,
       49,   90,   82,   47,   47,   83,   47,   48,   47,   76,
       91,   78,   79,   77,   63,   84,   85,   80,   93,   86,
       63,   81,   81,   92,   87,   90,   94,   89,   88,   96,
       97,   89,   99,   98,  100,  101,   91,  102,  103,  104,
      105,  106,  112,  108,  343,  109,  113,  110,   93,   99,
      107,  342,  111,  102,  104,  115,  112,   96,   94,   98,

      103,   97,   97,  114,  107,  103,  100,  109,  106,  105,
      101,  108,  105,  110,  111,  112,  113,  115,  118,  112,
      107,  119,  111,  129,  130,  114,  132,  114,  129,  131,
      134,  133,  137,  135,  138,  139,  136,  144,  143,  140,
      141,  118,  142,  145,  119,  133,  146,  131,  134,  150,
      132,  135,  136,  140,  147,  141,  130,  148,  151,  152,
      142,  145,  137,  143,  144,  138,  139,  139,  147,  153,
      154,  148,  155,  156,  158,  159,  150,  146,  160,  161,
      162,  163,  151,  165,  166,  151,  164,  153,  168,  167,
      154,  152,  169,  170,  171,  156,  172,  158,  177,  173,

      188,  176,  178,  161,  189,  155,  166,  167,  169,  159,
      160,  190,  177,  162,  163,  165,  164,  173,  176,  191,
      168,  171,  172,  194,  170,  196,  178,  197,  198,  190,
      188,  199,  203,  200,  189,  204,  205,  207,  210,  206,
      209,  211,  191,  212,  194,  215,  214,  221,  222,  218,
      198,  216,  217,  219,  205,  211,  196,  200,  209,  197,
      220,  204,  203,  206,  199,  216,  217,  218,  210,  207,
      214,  223,  224,  212,  225,  219,  226,  221,  227,  215,
      222,  229,  220,  230,  234,  233,  235,  238,  224,  239,
      247,  240,  226,  223,  245,  246,  248,  253,  249,  227,

      251,  238,  234,  254,  225,  240,  255,  256,  247,  235,
      260,  257,  258,  259,  230,  249,  229,  233,  261,  246,
      245,  239,  253,  262,  251,  263,  256,  264,  248,  257,
      258,  266,  255,  259,  261,  254,  267,  269,  271,  262,
      270,  272,  260,  273,  277,  279,  280,  266,  281,  285,
      283,  284,  289,  264,  286,  263,  292,  288,  269,  293,
      277,  294,  301,  272,  299,  273,  289,  296,  267,  271,
      270,  279,  286,  288,  292,  304,  303,  293,  306,  280,
      281,  283,  284,  299,  308,  296,  285,  313,  314,  301,
      318,  315,  319,  294,  303,  321,  320,  323,  327,  304,

      322,  328,  308,  330,  329,  333,  314,  315,  318,  334,
      306,  336,  337,  313,  340,  323,  344,  341,  345,  339,
      330,  321,  329,  319,  320,  338,  322,  333,  328,  335,
      327,  337,  332,  331,  344,  345,  326,  325,  317,  316,
      312,  334,  336,  311,  310,  309,  307,  305,  302,  300,
      298,  297,  340,  348,  348,  348,  349,  295,  349,  351,
      291,  351,  352,  352,  352,  353,  290,  353,  354,  354,
      354,  355,  287,  355,  282,  278,  276,  274,  268,  265,
      252,  250,  244,  243,  242,  241,  237,  236,  232,  231,
      228,  213,  208,  202,  201,  195,  193,  192,  186,  185,

      184,  183,  182,  181,  180,  175,  174,  157,  149,  128,
      127,  126,  125,  124,  123,  122,  121,  120,   95,   72,
       70,   69,   68,   67,   64,   62,   61,   57,   55,   52,
       29,   27,   26,   25,   21,   20,   17,   14,   12,    7,
        5,    3,    2,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[107] =
    {   0,
1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jzero.l"
/* -*-bison-*- */
/* Simple wc implementation in Flex */
#define YY_NO_INPUT 1
#line 9 "jzero.l"
#include "defs.h"
extern int handle_token(int category_value);
int rows = 0, words = 0, chars = 0;
#line 752 "lex.yy.c"
#line 753 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 14 "jzero.l"

#line 973 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 644 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "jzero.l"
{ rows++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "jzero.l"
{ /* no-op, discard comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 17 "jzero.l"
{ /* no-op, discard multi-line comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "jzero.l"
{ /* no-op, discard whitespace */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "jzero.l"
{ return handle_token(BOOLEAN); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "jzero.l"
{ return handle_token(BREAK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "jzero.l"
{ return handle_token(CASE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "jzero.l"
{ return handle_token(CHAR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "jzero.l"
{ return handle_token(CLASS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "jzero.l"
{ return handle_token(CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "jzero.l"
{ return handle_token(DEFAULT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "jzero.l"
{ return handle_token(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "jzero.l"
{ return handle_token(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "jzero.l"
{ return handle_token(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 31 "jzero.l"
{ return handle_token(FOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "jzero.l"
{ return handle_token(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "jzero.l"
{ return handle_token(INSTANCEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "jzero.l"
{ return handle_token(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "jzero.l"
{ return handle_token(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "jzero.l"
{ return handle_token(NEW); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "jzero.l"
{ return handle_token(PUBLIC); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "jzero.l"
{ return handle_token(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "jzero.l"
{ return handle_token(STATIC); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "jzero.l"
{ return handle_token(SWITCH); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "jzero.l"
{ return handle_token(VOID); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "jzero.l"
{ return handle_token(WHILE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "jzero.l"
{return handle_token(FLOAT_LITERAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "jzero.l"
{ return handle_token(INTEGER_LITERAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "jzero.l"
{ return handle_token(EQUALS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "jzero.l"
{ return handle_token(PLUS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "jzero.l"
{ return handle_token(MINUS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "jzero.l"
{ return handle_token(MULTIPLY); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "jzero.l"
{ return handle_token(DIVIDE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "jzero.l"
{ return handle_token(MODULO); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "jzero.l"
{ return handle_token(INCREMENT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "jzero.l"
{ return handle_token(DECREMENT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "jzero.l"
{ return handle_token(IS_EQUAL_TO); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "jzero.l"
{ return handle_token(NOT_EQUAL_TO); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "jzero.l"
{ return handle_token(GREATER_THAN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "jzero.l"
{ return handle_token(LESS_THAN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "jzero.l"
{ return handle_token(GREATER_THAN_EQUAL); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "jzero.l"
{ return handle_token(LESS_THAN_EQUAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "jzero.l"
{ return handle_token(LOGICAL_AND); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "jzero.l"
{ return handle_token(LOGICAL_OR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "jzero.l"
{ return handle_token(LOGICAL_NOT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "jzero.l"
{ return handle_token(LEFT_BRACKET); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "jzero.l"
{ return handle_token(RIGHT_BRACKET); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "jzero.l"
{ return handle_token(DOT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "jzero.l"
{ return handle_token(TYPE); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 70 "jzero.l"
{ return handle_token(STRING_LITERAL); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "jzero.l"
{ return handle_token(CHAR_LITERAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "jzero.l"
{ return handle_token(CHAR_LITERAL); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "jzero.l"
{ return handle_token(CHAR_LITERAL); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "jzero.l"
{ return handle_token(CHAR_LITERAL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "jzero.l"
{ return handle_token(CHAR_LITERAL); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "jzero.l"
{ return handle_token(INVALID_CHAR_LITERAL); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "jzero.l"
{ return handle_token(BOOLEAN_LITERAL); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "jzero.l"
{ return handle_token(BOOLEAN_LITERAL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "jzero.l"
{ return handle_token(INVALID_CHAR_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "jzero.l"
{ return handle_token(LEFT_PARENTHESIS); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "jzero.l"
{ return handle_token(RIGHT_PARENTHESIS); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "jzero.l"
{ return handle_token(COMMA); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "jzero.l"
{ return handle_token(SEMICOLON); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 "jzero.l"
{ return handle_token(LEFT_BRACE); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "jzero.l"
{ return handle_token(RIGHT_BRACE); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "jzero.l"
{ return handle_token(COLON); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "jzero.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "jzero.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "jzero.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "jzero.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "jzero.l"
{return handle_token(INVALID_PUNCTUATION); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 100 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 101 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 102 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 103 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 104 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 105 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 106 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 107 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 108 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 109 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 110 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 111 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 112 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 113 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 114 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 115 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 116 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 117 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 118 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 119 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 120 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 121 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 122 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 123 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 124 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 125 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 126 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 127 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 128 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 129 "jzero.l"
{ return handle_token(NOT_IN_JZERO_RESERVED); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 131 "jzero.l"
{ words++; chars += strlen(yytext); return handle_token(WORD); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 132 "jzero.l"
{ chars++; return handle_token(UNRECOGNIZED_CHARACTER); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 133 "jzero.l"
ECHO;
	YY_BREAK
#line 1574 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "jzero.l"


